return
{
    enable = true,
    descriptionWidth = 75,
    noResize = "",
    W = 400,
    noMove = "",
    H = 300,
    X = 0,
    configurationWindowEnable = false,
    noTitleBar = "",
    Y = 0,
    transparentWindow = false,
    globalFlags = 
    {
        {
            enable = true,
            flagMask = 0x000001FC,
            flagNum = 0x0000000B,
            hexdisplay = false,
            description = "Lucky Coins",
        },
        {
            enable = true,
            flagMask = 0x000000FF,
            flagNum = 0x0000000F,
            hexdisplay = false,
            description = "MA4 Tickets",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x0000000E,
            hexdisplay = false,
            description = "MA4 Kills (Total)",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x00000003,
            hexdisplay = false,
            description = "MA4 Kills (Central Dome)",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x00000004,
            hexdisplay = false,
            description = "MA4 Kills (Gal Da Val)",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x00000008,
            hexdisplay = false,
            description = "MA4 Kills (Crater)",
        },
        {
            enable = false,
            flagMask = 0x10000000,
            flagNum = 0x00000009,
            hexdisplay = false,
            description = "AOL CUP -Sunset Base- (Mag Cell)",
        },
    },
    anchor = 3,
}
