return
{
    enable = true,
    descriptionWidth = 66,
    noResize = "NoResize",
    W = 150,
    noMove = "NoMove",
    H = 48,
    X = 0,
    configurationWindowEnable = false,
    noTitleBar = "NoTitleBar",
    Y = 0,
    transparentWindow = false,
    globalFlags = 
    {
        {
            enable = true,
            flagMask = 0x000001FC,
            flagNum = 0x0000000B,
            hexdisplay = false,
            description = "Lucky Coins",
        },
        {
            enable = true,
            flagMask = 0x000000FF,
            flagNum = 0x0000000F,
            hexdisplay = false,
            description = "MA4 Tickets",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x0000000E,
            hexdisplay = false,
            description = "MA4 Kills (Total)",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x00000003,
            hexdisplay = false,
            description = "MA4 Kills (Central Dome)",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x00000004,
            hexdisplay = false,
            description = "MA4 Kills (Gal Da Val)",
        },
        {
            enable = false,
            flagMask = 0x7FFFFFFF,
            flagNum = 0x00000008,
            hexdisplay = false,
            description = "MA4 Kills (Crater)",
        },
        {
            enable = false,
            flagMask = 0x10000000,
            flagNum = 0x00000009,
            hexdisplay = false,
            description = "AOL CUP -Sunset Base- (Mag Cell)",
        },
        {
            enable = false,
            flagMask = 0x00003FFF,
            flagNum = 0x00000009,
            hexdisplay = false,
            description = "MA1v2 Points",
        },
        {
            enable = false,
            flagMask = 0x000000FF,
            flagNum = 0x00000003,
            hexdisplay = false,
            description = "MA1v2 Tickets",
        },
        {
            enable = false,
            flagMask = 0x0FFFC000,
            flagNum = 0x00000009,
            hexdisplay = false,
            description = "MA2v2 Points",
        },
        {
            enable = false,
            flagMask = 0x7FC00000,
            flagNum = 0x0000000A,
            hexdisplay = false,
            description = "MA2v2 Tickets",
        },
    },
    anchor = 3,
}
